travis:
  secure:
    BINSTAR_TOKEN: OimBrNtliTum6Q1hmV+ifiI0RWOfVQleh2KExjh06wFAchW+GiNG8lWTQcr1mVicL0+mM0w3lJmquofaSEcQZSQzQXExwdsC5OMJbn3HGZ2b4K2v5qgo1D8AKg6v4gawjTliTo4JZE4Ql8DMatrkEMnYMyYMdvgDIuxhzwI1hxyUR7zlcL+kvQQgg4qMXe4+TaGnOk6IAryQ6HWMQQ0UrLvujPH6SQeGiDwxwqG30uPygj7La89khfUNLrdl6PWiE78Xvyo9RIahCHIjdo/erdhEceAarmF7ooGR6irjJ+lEHASQ147w1a0jy23bb1MCagIT/K2ByNRt7COCGBIjrqAqNjsLDCfUz5TPDhS1twlsvMtxrvWj309tzv8wNQHV9OPUt1MYimj3eJP6+X0wLxx3iytQQPsjgH6IGPI9UCzL3JUagxE90hKM6EV5zMm34+5gtNFDDozR7YaUZXN6LL5ynf08sJWT5e2TDckszuZNf257Hnkwr39Rp8p8TcM3eVm7tEZIxQoJ+XZZGlQv/0iPhi0OgHI4ffaQvzZU3Zh804oIWKsQBsi4kTK+CLfv2SpQkObzcqOef3ZZAavkvVEqrlgGNralgfxpNjLj0dp4ZSN+ucI5QTyhTAAvs26FZ2OnLEwZBzU6tkfVE5qWt/MMxLCyoSqoiv72/SspQzc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
